version: '3.8'
services:
  database:
    build: postgres
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  scrapy:
    build: Scrapy
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
volumes:
  database-data: